source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'spring',        group: :development
gem 'rspec-rails'
gem 'factory_girl_rails'
gem 'simplecov'
gem 'rubocop'
gem 'angularjs-rails'
gem 'rack-cors', require: 'rack/cors'
gem 'capistrano'
gem 'capistrano-rails', '~> 1.1.0'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
gem 'thin'
# gem 'turbolinks'
# gem 'jbuilder', '~> 2.0'
# gem 'sdoc', '~> 0.4.0',          group: :doc